apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-external
  namespace: idp
spec:
  type: NodePort
  selector:
    app: cockroachdb
  ports:
    - name: sql
      protocol: TCP
      port: 26257
      targetPort: 26257
      nodePort: 32057