apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-backend
  namespace: idp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idp
  template:
    metadata:
      labels:
        app: idp
    spec:
      containers:
        - name: idp
          image: BACKEND_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 4000 
          env:
            - name: DB_HOST
              value: cockroachdb.idp.svc.cluster.local
            - name: DB_NAME
              value: "idp" 
            - name: DB_USER
              value: "root"
            - name: DB_PORT
              value: "26257"